name: Update Air Quality Data
on:
  schedule:
    - cron: '*/30 * * * *' # 10분마다 (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-data # 동일 그룹 내 작업을 순차적으로 처리
  cancel-in-progress: false # 진행 중인 작업을 취소하지 않음
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run update-air-quality
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add air-quality-data.json
           git diff --staged --quiet || (git commit -m "Update air-quality-data.json" && git pull origin main --rebase && git push)
