name: Update Air Quality Data
on:
  schedule:
    - cron: 0/10 * * * *
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  cancel-in-progress: false
  group: update-data-air-quality
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm install puppeteer # Puppeteer 설치 명시
      - run: npm run update-air-quality
      - name: Check file changes and commit
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add air-quality-data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update air-quality-data.json"
            git push origin main
          fi
