name: Update Earthquake Data
on:
  schedule:
    - cron: '*/20 * * * *' # 10분마다 (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-data-earthquake
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm install cheerio node-fetch puppeteer
      - run: node update-earthquake-data.js
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add earthquake-data.json
          # 변경 사항이 있을 때만 커밋하고, unstaged changes를 강제로 처리
          git diff --staged --quiet || (git commit -m "Update earthquake-data.json" || git stash && git stash drop)
          git pull origin main --rebase
          git push origin main
